// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgdeakaftkjjcnsmsfap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnZGVha2FmdGtqamNuc21zZmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMDMxNjAsImV4cCI6MjA4NDU3OTE2MH0.d7u6JflxkVlpZzVkXzjgXH-7im90qbJaGmX1fuDOWIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});